name: Release
on:
  schedule:
    - cron: "23 */4 * * *"
  push:
    branches:
      - main
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.event_name, github.ref_name) }}
permissions:
  contents: none
  deployments: none
  actions: none
  checks: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  hugo_extended_edition_release:
    name: Hugo Release Extended Edition
    permissions:
      contents: read
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: get_latest_release
        run: |
          export tag=$(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases | jq -r 'first(.[] | select(.prerelease == false and .draft == false)) | .tag_name' | sed s/^v//)
          echo "::notice title=Hugo Latest Release::Found ${tag} latest release tag name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0
      - name: Generate Extended PKGBUILD
        run: |
          if [[ '${{ github.event_name == 'schedule' }}' == 'true' ]]; then
            export NO_PKGREL_INCREMENT=1
          fi
          VERSION_NUMBER=${{ steps.get_latest_release.outputs.tag }} ./hugo/pkgbuild-extended.sh
          cat PKGBUILD
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: gohugo-extended-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          allow_empty_commits: false
          test: true
  docker_credential_pass_bin_release:
    name: Release
    permissions:
      contents: read
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: get_latest_release
        run: |
          export tag=$(wget -qO- https://api.github.com/repos/docker/docker-credential-helpers/releases | jq -r 'first(.[] | select(.prerelease == false and .draft == false)) | .tag_name' | sed s/^v//)
          echo "::notice title=Upstream Latest Release::Found ${tag} latest release tag name"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0
      - name: Generate PKGBUILD
        run: |
          if [[ '${{ github.event_name == 'schedule' }}' == 'true' ]]; then
            export NO_PKGREL_INCREMENT=1
          fi
          VERSION_NUMBER=${{ steps.get_latest_release.outputs.tag }} ./docker-credential-pass-bin/pkgbuild.sh
          cat PKGBUILD
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: docker-credential-pass-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          allow_empty_commits: false
          test: true
